env:
  global:
    secure: "O2t+eRfD+Diemym426Z5dgRw77qzb3NcmsY2ZBebnlgxQAY7pp8ae0Xg9uTOj1blmRt7yvfoO0ShSkxuQHbkt2aE/9GC4l5oXm3jx+RdAnZy+8+42KFjZ4ruonmhYAsgqSZaumCdIvJMwG1/yGsePVD+lcKB/xUpy+EY1syuAxvTmXlwAx/nPPu2S2qyjIiPnCPLJT/qH1J+8pgub/FAJYYDGjA0wQdCmjyKOmql50L3osY9S1YeaFR7TG06Un5JDfIWN9NMrfxOZNPk8Q5ouD9fSm1k6WqdP8lSeG6L+fxTuz88fqdjOb+OstOOvBbL3gVmB+bXztZ03ev6/9s55M8xu7OWni71OVVVrHpqUpe2lTHdGzCZO+U91yDmTSMRTEzGNfV6udEfrYIOJADFwGJLIp+W5HgxiyHcgwo4DV3QdSW3bljEJUofqFAaWIuzLtCA48hTwnno4gH4BujQobscRW3s2/1xATi3IOSe5t7alt2rZYFcJ5FM3imkI8yQsDlTCtW344oKzqvkzZFrSn+OQIV+UmnnSoXVo4uLdw6jqcQOQTvxT5gJNSyEvBtmcJJsIcVFEsU2O1EnqLNafjejKhGCeXLBOnnoifDtTzoxCQnc7BqpdXtjAf81wpwZxzziEHOguHqAkd9Tt5ntjpLHPMCDkwphu3VSFoyWuy8="

jobs:
  include:
    - os: linux
      dist: xenial
      name: "Xenial"
      language: shell

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - while read line; do
      export api=$(echo $line | cut -d' ' -f1);
      export ver=$(echo $line | cut -d' ' -f2);
      export apifile="${api}-${ver}.json"
      export v2_url="https://${api}.googleapis.com/\$discovery/rest?version=${ver}";
      export v1_url="https://www.googleapis.com/discovery/v1/apis/${api}/${ver}/rest";
      echo "Checking v2 URL for $api $ver...";
      curl -s --compressed -f -o ~/$apifile $v2_url;
      export result=$?;
      if [ $result -ne 0 ]; then
        echo "v2 URL failed with $result, checking v1 URL for $api $ver...";
        curl -s --compressed -f -o ~/$apifile $v1_url;
        export result=$?;
        if [ $result -ne 0 ]; then
          echo "v1 failed also! Giving up.";
          exit 1;
        fi;
      fi;
      cat ~/$apifile | python3 -c "import json, sys, collections; myjson = json.loads(sys.stdin.read()); myjson.pop('etag', None); myjon.pop('revision', None); print(json.dumps(mydict, indent=2, sort_keys=True))" > $apifile; 
    done < apis.txt
  - git add .
  - git diff --quiet && git diff --staged --quiet || git commit -am 'API changes [ci skip]'
  - echo "https://${token}@github.com" > ~/.git_credentials
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git remote add origin-gh https://${token}@github.com/$TRAVIS_REPO_SLUG.git > /dev/null 2>&1
  - git push --quiet --set-upstream origin-gh master
