name: Check for API updates

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '37 4,18,22 * * *'

jobs:
  check-apis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Check for updates
        run: bash check-apis.sh

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git add *
          git diff --quiet && git diff --staged --quiet || git commit -am 'API changes [ci skip]'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
